// apps/react/src/render/sections/RenderNoter.tsx
import type {
  Arsredovisning,
  Verksamhetsar,
} from "@/model/arsredovisning/Arsredovisning.ts";
import type { TaxonomyItem } from "@/model/taxonomy/TaxonomyItem.ts";
import type { TaxonomyManager } from "@/util/TaxonomyManager.ts";
import {
  getTaxonomyItemForBelopprad,
  isBeloppradInTaxonomyItemList,
} from "@/model/arsredovisning/Belopprad.ts";
import {
  getHeaderBeloppraderForNoter,
  getPeriodTypeForGroup,
} from "@/util/noterUtils.ts";
import { RenderBelopprad } from "@/render/belopprad/RenderBelopprad.tsx";

// Dölj "förändringar av [anskaffningsvärden/avskrivningar/...]"-rubriker.
function shouldHideTaxonomyItem(taxonomyItemName: string): boolean {
  return (
    taxonomyItemName.endsWith("ForandringAnskaffningsvardenAbstract") ||
    taxonomyItemName.endsWith("ForandringAvskrivningarAbstract") ||
    taxonomyItemName.endsWith("ForandringUppskrivningarAbstract") ||
    taxonomyItemName.endsWith("ForandringNedskrivningarAbstract")
  );
}

/**
 * Värdekolumnens tabellhuvudcell för en grupp — React-port av den Vue-lokala
 * getValueColumnHeaderCell (som returnerade en VNode).
 */
function ValueColumnHeader(props: {
  groupTaxonomyItem: TaxonomyItem;
  noter: Arsredovisning["noter"];
  verksamhetsar: Verksamhetsar;
}) {
  const periodType = getPeriodTypeForGroup(props.groupTaxonomyItem, props.noter);
  if (periodType === "duration") {
    return (
      <th scope="col" className="value-container">
        {props.verksamhetsar.startdatum}
        <br />–{props.verksamhetsar.slutdatum}
      </th>
    );
  }
  if (periodType === "instant") {
    return (
      <th scope="col" className="value-container">
        {props.verksamhetsar.slutdatum}
      </th>
    );
  }
  return <th scope="col" className="value-container"></th>;
}

/** Port av RenderNoter.vue — noter grupperade med numrering. */
export function RenderNoter(props: {
  arsredovisning: Arsredovisning;
  taxonomyManager: TaxonomyManager;
}) {
  const { arsredovisning, taxonomyManager } = props;
  if (arsredovisning.noter.length === 0) return null;

  const tidigare = arsredovisning.verksamhetsarTidigare;
  const headerGroups = getHeaderBeloppraderForNoter(
    taxonomyManager,
    arsredovisning.noter,
  );

  return (
    <div className="noter">
      <h2>Noter</h2>
      {headerGroups.map(
        (
          { belopprad: headerBelopprad, taxonomyItem: headerTaxonomyItem },
          index,
        ) => (
          <table key={headerBelopprad.taxonomyItemName} className="noter-table">
            <thead>
              <tr>
                <th scope="col">
                  <h3>
                    {`Not ${index + 1}: ${headerTaxonomyItem.additionalData.displayLabel}`}
                  </h3>
                </th>
                <ValueColumnHeader
                  groupTaxonomyItem={headerTaxonomyItem}
                  noter={arsredovisning.noter}
                  verksamhetsar={arsredovisning.verksamhetsarNuvarande}
                />
                {tidigare.length > 0 && (
                  <ValueColumnHeader
                    groupTaxonomyItem={headerTaxonomyItem}
                    noter={arsredovisning.noter}
                    verksamhetsar={tidigare[0]}
                  />
                )}
              </tr>
            </thead>
            <tbody>
              {arsredovisning.noter
                .filter(
                  (belopprad) =>
                    !shouldHideTaxonomyItem(belopprad.taxonomyItemName) &&
                    isBeloppradInTaxonomyItemList(
                      [headerTaxonomyItem, ...headerTaxonomyItem.childrenFlat],
                      belopprad,
                    ),
                )
                .map((belopprad) => (
                  <RenderBelopprad
                    key={belopprad.taxonomyItemName}
                    belopprad={belopprad}
                    comparableNumPreviousYears={Math.min(tidigare.length, 1)}
                    redovisningsvaluta={
                      arsredovisning.redovisningsinformation.redovisningsvaluta
                    }
                    stringShowHeader={
                      getTaxonomyItemForBelopprad(taxonomyManager, belopprad)
                        .additionalData.displayLabel !==
                      headerTaxonomyItem.additionalData.displayLabel
                    }
                    taxonomyManager={taxonomyManager}
                    monetaryShowBalanceSign
                  />
                ))}
            </tbody>
          </table>
        ),
      )}
    </div>
  );
}

// src/components/render/sections/RenderNoter.vue
<script lang="ts" setup>
/**
 * En komponent för att rendera noter i årsredovisningen.
 * Visar noter grupperade efter typ med korrekt numrering och formatering.
 */

import type { Arsredovisning } from "@/model/arsredovisning/Arsredovisning.ts";
import RenderBelopprad from "@/components/render/blocks/RenderBelopprad.vue";
import { getTaxonomyManager } from "@/util/TaxonomyManager.ts";
import {
  getTaxonomyItemForBelopprad,
  isBeloppradInTaxonomyItemList,
} from "@/model/arsredovisning/Belopprad.ts";
import { getHeaderBeloppraderForNoter } from "@/util/noterUtils.ts";
import { getValueColumnHeaderCell } from "@/view/noterViewUtils.ts";
import { TaxonomyRootName } from "@/model/taxonomy/TaxonomyItem.ts";

const taxonomyManager = await getTaxonomyManager(TaxonomyRootName.NOTER);

const props = defineProps<{
  /** Årsredovisningen som innehåller noterna. */
  arsredovisning: Arsredovisning;
}>();

function shouldHideTaxonomyItem(taxonomyItemName: string) {
  // Dölj rubriker "förändringar av [anskaffningsvärden/avskrivningar/
  // uppskrivningar/nedskrivningar]", de syns normalt inte i årsredovsiningar.
  return (
    taxonomyItemName.endsWith("ForandringAnskaffningsvardenAbstract") ||
    taxonomyItemName.endsWith("ForandringAvskrivningarAbstract") ||
    taxonomyItemName.endsWith("ForandringUppskrivningarAbstract") ||
    taxonomyItemName.endsWith("ForandringNedskrivningarAbstract")
  );
}
</script>

<template>
  <div v-if="arsredovisning.noter.length > 0">
    <h2>Noter</h2>
    <table
      v-for="(
        { belopprad: headerBelopprad, taxonomyItem: headerTaxonomyItem }, index
      ) in getHeaderBeloppraderForNoter(taxonomyManager, arsredovisning.noter)"
      :key="headerBelopprad.taxonomyItemName"
    >
      <thead>
        <tr>
          <th scope="col">
            <h3>
              {{
                "Not " +
                (index + 1) +
                ": " +
                headerTaxonomyItem.additionalData.displayLabel
              }}
            </h3>
          </th>
          <component
            :is="
              getValueColumnHeaderCell(
                headerTaxonomyItem,
                arsredovisning.noter,
                arsredovisning.verksamhetsarNuvarande,
              )
            "
          />
          <component
            :is="
              getValueColumnHeaderCell(
                headerTaxonomyItem,
                arsredovisning.noter,
                arsredovisning.verksamhetsarTidigare[0],
              )
            "
            v-if="arsredovisning.verksamhetsarTidigare.length > 0"
          />
        </tr>
      </thead>
      <tbody>
        <RenderBelopprad
          v-for="belopprad in props.arsredovisning.noter.filter(
            (belopprad) =>
              !shouldHideTaxonomyItem(belopprad.taxonomyItemName) &&
              isBeloppradInTaxonomyItemList(
                [headerTaxonomyItem, ...headerTaxonomyItem.childrenFlat],
                belopprad,
              ),
          )"
          :key="belopprad.taxonomyItemName"
          :belopprad="belopprad"
          :comparable-num-previous-years="
            Math.min(arsredovisning.verksamhetsarTidigare.length, 1)
          "
          :redovisningsvaluta="
            arsredovisning.redovisningsinformation.redovisningsvaluta
          "
          :string-show-header="
            getTaxonomyItemForBelopprad(taxonomyManager, belopprad)
              .additionalData.displayLabel !==
            headerTaxonomyItem.additionalData.displayLabel
          "
          :taxonomy-manager="taxonomyManager"
          monetary-show-balance-sign
        />
      </tbody>
    </table>
  </div>
</template>

<style lang="scss" scoped>
h3 {
  margin-bottom: 0;
}

table {
  margin-bottom: 2rem;

  :deep(.level-2) {
    .header {
      text-decoration: underline;
    }

    td {
      padding-bottom: 0 !important;
    }
  }

  :deep(.level-3) {
    .header {
      font-weight: 500;
    }
  }
}
</style>
