// src/components/edit/sections/EditNoter.vue
<script lang="ts" setup>
/**
 * En komponent för att redigera noter i årsredovisningen.
 * Visar noter grupperade efter typ och tillåter användaren att lägga till, redigera och ta bort noter.
 */

import { type Arsredovisning } from "@/model/arsredovisning/Arsredovisning.ts";
import EditBelopprad from "@/components/edit/blocks/EditBelopprad.vue";
import { createBelopprad } from "@/model/arsredovisning/Belopprad.ts";
import { getTaxonomyManager } from "@/util/TaxonomyManager.ts";
import { getValueColumnHeaderCell } from "@/view/noterViewUtils.ts";
import { usePrepopulateSection } from "@/components/edit/composables/usePrepopulateSection.ts";
import { TaxonomyRootName } from "@/model/taxonomy/TaxonomyItem.ts";
import BaseEditBeloppradTitle from "@/components/edit/blocks/belopprad/BaseEditBeloppradTitle.vue";
import CommonAccordion from "@/components/common/CommonAccordion.vue";
import CommonAccordionItem from "@/components/common/CommonAccordionItem.vue";
import { computed, ref } from "vue";
import CommonClearableInput from "@/components/common/CommonClearableInput.vue";

// TaxonomyManager och rader
const taxonomyManager = await getTaxonomyManager(TaxonomyRootName.NOTER);
const availableTaxonomyItems = taxonomyManager.getRoot();

// Data
/** Årsredovisningen som innehåller noterna. */
const arsredovisning = defineModel<Arsredovisning>("arsredovisning", {
  required: true,
});

const { prepopulateSection, groupPrepopulatedSection } = usePrepopulateSection({
  taxonomyManager,
  availableTaxonomyItems,
  arsredovisning: arsredovisning,
  sectionName: "noter",
  maxNumPreviousYears: 1,
});

const groupsOfGroups = availableTaxonomyItems.children[0].children;

const belopprader = prepopulateSection();
const groups = availableTaxonomyItems.children[0].children.flatMap(
  (c) => c.children,
);
const groupedBelopprader = groupPrepopulatedSection(belopprader, groups);

const filter = ref<string>("");
const visibleGroups = computed(() => {
  if (!filter.value) {
    return groups;
  }

  return groups.filter((g) =>
    g.additionalData.displayLabel
      ?.toLowerCase()
      ?.includes(filter.value.toLowerCase()),
  );
});
</script>

<template>
  <div class="d-flex flex-column">
    <div class="filter-container">
      <div class="filter-contents">
        <div class="d-flex flex-col align-items-center gap-2">
          <label for="edit-noter-filter">Filtrera noter:</label>
          <CommonClearableInput
            id="edit-noter-filter"
            v-model="filter"
            class="form-control"
            name="edit-noter-filter"
            placeholder='T.ex. "medelantalet anställda"…'
          />
        </div>

        <hr />
      </div>
    </div>

    <div v-if="visibleGroups.length < 1" class="mt-4">
      Inga noter matchade filtreringen.
    </div>

    <div class="d-flex flex-column gap-4 mt-4">
      <div
        v-for="groupOfGroups in groupsOfGroups.filter((gg) =>
          gg.children.some((g) => visibleGroups.includes(g)),
        )"
        :key="groupOfGroups.xmlName"
      >
        <div class="mb-2">
          <BaseEditBeloppradTitle
            :belopprad="createBelopprad(groupOfGroups)"
            :taxonomy-manager="taxonomyManager"
          />
        </div>

        <CommonAccordion>
          <CommonAccordionItem
            v-for="[groupIndex, group] in [...groups.entries()].filter(
              ([, g]) =>
                groupOfGroups.children.includes(g) && visibleGroups.includes(g),
            )"
            :id="`noter-accordion-${group.xmlName}`"
            :key="group.xmlName"
            :title="group.additionalData.displayLabel"
          >
            <table>
              <thead v-if="groupedBelopprader[groupIndex].length > 1">
                <tr>
                  <th scope="col">{{ group.additionalData.displayLabel }}</th>
                  <component
                    :is="
                      getValueColumnHeaderCell(
                        group,
                        arsredovisning.noter,
                        arsredovisning.verksamhetsarNuvarande,
                      )
                    "
                  />
                  <component
                    :is="
                      getValueColumnHeaderCell(
                        group,
                        arsredovisning.noter,
                        arsredovisning.verksamhetsarTidigare[0],
                      )
                    "
                    v-if="arsredovisning.verksamhetsarTidigare.length > 0"
                  />
                </tr>
              </thead>
              <tbody>
                <EditBelopprad
                  v-for="(belopprad, index) in groupedBelopprader[groupIndex]"
                  :key="belopprad.taxonomyItemName"
                  v-model:belopprad="groupedBelopprader[groupIndex][index]"
                  v-model:belopprader="groupedBelopprader[groupIndex]"
                  :comparable-num-previous-years="
                    Math.min(arsredovisning.verksamhetsarTidigare.length, 1)
                  "
                  :string-minimum-level="1"
                  :taxonomy-manager="taxonomyManager"
                  monetary-show-balance-sign
                  string-multiline
                />
              </tbody>
            </table>
          </CommonAccordionItem>
        </CommonAccordion>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
@import "@/assets/_variables.scss";

// Det här är ganska fult...
.filter-container {
  position: sticky;
  z-index: 10;
  top: $spacing-md;

  .filter-contents {
    background: $background-light;

    margin-top: -$spacing-xl;
    margin-left: -$spacing-md;
    width: calc(100% + 2 * #{$spacing-md});
    padding-left: $spacing-md;
    padding-right: $spacing-md;
    padding-top: $spacing-xl;
  }

  hr {
    margin-top: $spacing-lg;
    margin-bottom: 0;
  }

  :deep(input) {
    flex: 1;
  }
}
</style>

// apps/react/src/edit/sections/EditNoter.tsx
import { useEffect, useMemo, useState } from "react";
import "@/edit/belopprad/editBelopprad.scss";
import type { Verksamhetsar } from "@/model/arsredovisning/Arsredovisning.ts";
import type { Belopprad } from "@/model/arsredovisning/Belopprad.ts";
import type { TaxonomyItem } from "@/model/taxonomy/TaxonomyItem.ts";
import { TaxonomyRootName } from "@/model/taxonomy/TaxonomyItem.ts";
import {
  getTaxonomyManager,
  type TaxonomyManager,
} from "@/util/TaxonomyManager.ts";
import { getPeriodTypeForGroup } from "@/util/noterUtils.ts";
import { useArsredovisningStore } from "@/stores/arsredovisningStore.ts";
import { Input } from "@/components/ui/input.tsx";
import { BeloppradEditContext } from "@/edit/belopprad/BeloppradEditContext.ts";
import { usePrepopulateSection } from "@/edit/belopprad/usePrepopulateSection.ts";
import { groupPool } from "@/edit/belopprad/prepopulate.ts";
import { EditBelopprad } from "@/edit/belopprad/EditBelopprad.tsx";
import { EditGroup } from "@/edit/EditGroup.tsx";

const MAX_NUM_PREVIOUS_YEARS = 1;

/** Värdekolumnens tabellhuvudcell för en not-grupp (period/instant/tomt). */
function ValueColumnHeader({
  group,
  noter,
  verksamhetsar,
}: {
  group: TaxonomyItem;
  noter: Belopprad[];
  verksamhetsar: Verksamhetsar;
}) {
  const periodType = getPeriodTypeForGroup(group, noter);
  if (periodType === "duration") {
    return (
      <th scope="col" className="value-container">
        {verksamhetsar.startdatum}
        <br />–{verksamhetsar.slutdatum}
      </th>
    );
  }
  if (periodType === "instant") {
    return (
      <th scope="col" className="value-container">
        {verksamhetsar.slutdatum}
      </th>
    );
  }
  return <th scope="col" className="value-container"></th>;
}

/** Port av EditNoter.vue — noter grupperade per kategori, med filter. */
export function EditNoter() {
  const arsredovisning = useArsredovisningStore((s) => s.arsredovisning);
  useArsredovisningStore((s) => s.revision);
  const [taxonomyManager, setTaxonomyManager] = useState<TaxonomyManager | null>(
    null,
  );
  const [filter, setFilter] = useState("");

  useEffect(() => {
    let active = true;
    void getTaxonomyManager(TaxonomyRootName.NOTER).then((m) => {
      if (active) setTaxonomyManager(m);
    });
    return () => {
      active = false;
    };
  }, []);

  const availableTaxonomyItems = taxonomyManager
    ? taxonomyManager.getRoot()
    : null;

  const editor = usePrepopulateSection({
    taxonomyManager,
    availableTaxonomyItems,
    sectionName: "noter",
    maxNumPreviousYears: MAX_NUM_PREVIOUS_YEARS,
  });

  const { groups, groupsOfGroups } = useMemo(() => {
    if (!availableTaxonomyItems) {
      return { groups: [] as TaxonomyItem[], groupsOfGroups: [] as TaxonomyItem[] };
    }
    const gog = availableTaxonomyItems.children[0].children;
    return { groups: gog.flatMap((c) => c.children), groupsOfGroups: gog };
  }, [availableTaxonomyItems]);

  if (!arsredovisning || !editor || groups.length === 0) {
    return (
      <div className="rounded-lg border border-line bg-surface p-6 text-sm text-ink-light shadow-card">
        Laddar noter…
      </div>
    );
  }

  const numPreviousYears = Math.min(
    arsredovisning.verksamhetsarTidigare.length,
    MAX_NUM_PREVIOUS_YEARS,
  );
  const grouped = groupPool(editor.pool, groups);

  const visibleGroups = filter
    ? groups.filter((g) =>
        g.additionalData.displayLabel
          ?.toLowerCase()
          .includes(filter.toLowerCase()),
      )
    : groups;

  return (
    <BeloppradEditContext.Provider
      value={{
        taxonomyManager: editor.taxonomyManager,
        editField: editor.editField,
      }}
    >
      <div>
        <div className="sticky top-0 z-10 -mx-1 mb-4 bg-surface-medium/90 px-1 py-2 backdrop-blur">
          <Input
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            placeholder='Filtrera noter, t.ex. "medelantalet anställda"…'
          />
        </div>

        {visibleGroups.length === 0 && (
          <p className="text-sm text-ink-light">
            Inga noter matchade filtreringen.
          </p>
        )}

        <div className="space-y-6">
          {groupsOfGroups
            .filter((gog) =>
              gog.children.some((g) => visibleGroups.includes(g)),
            )
            .map((groupOfGroups) => (
              <div key={groupOfGroups.xmlName}>
                <h2 className="mb-3 text-base font-semibold text-ink">
                  {groupOfGroups.additionalData.displayLabel}
                </h2>
                <div className="space-y-4">
                  {groups
                    .map((group, groupIndex) => ({ group, groupIndex }))
                    .filter(
                      ({ group }) =>
                        groupOfGroups.children.includes(group) &&
                        visibleGroups.includes(group),
                    )
                    .map(({ group, groupIndex }) => (
                      <EditGroup
                        key={group.xmlName}
                        id={`noter-${group.xmlName}`}
                        title={group.additionalData.displayLabel ?? ""}
                      >
                        <div className="edit-belopprad-table">
                          <table>
                            {grouped[groupIndex].length > 1 && (
                              <thead>
                                <tr>
                                  <th scope="col">
                                    {group.additionalData.displayLabel}
                                  </th>
                                  <ValueColumnHeader
                                    group={group}
                                    noter={arsredovisning.noter}
                                    verksamhetsar={
                                      arsredovisning.verksamhetsarNuvarande
                                    }
                                  />
                                  {numPreviousYears > 0 &&
                                    arsredovisning.verksamhetsarTidigare[0] && (
                                      <ValueColumnHeader
                                        group={group}
                                        noter={arsredovisning.noter}
                                        verksamhetsar={
                                          arsredovisning.verksamhetsarTidigare[0]
                                        }
                                      />
                                    )}
                                </tr>
                              </thead>
                            )}
                            <tbody>
                              {grouped[groupIndex].map((belopprad) => (
                                <EditBelopprad
                                  key={`${belopprad.taxonomyItemName}-${belopprad.labelType ?? ""}`}
                                  belopprad={belopprad}
                                  comparableNumPreviousYears={numPreviousYears}
                                  stringMinimumLevel={1}
                                  monetaryShowBalanceSign
                                  stringMultiline
                                />
                              ))}
                            </tbody>
                          </table>
                        </div>
                      </EditGroup>
                    ))}
                </div>
              </div>
            ))}
        </div>
      </div>
    </BeloppradEditContext.Provider>
  );
}
